In [5]:
import numpy as np
print(np.__version__)


2.3.2


In [ ]:
data=np.random.randint(0,10,(3,3))
data

array([[0, 3, 7],
       [1, 9, 8],
       [8, 2, 9]], dtype=int32)

In [12]:
np.random.randn(3,3)

array([[ 0.87938044, -0.03276469,  0.01852048],
       [ 1.4607248 ,  0.01376347, -0.78626252],
       [ 1.38458578, -1.02805747, -0.59781206]])

In [ ]:
np.random.randn(3,3).std()#it is closed to 1

np.float64(1.0930395642987956)

In [ ]:
np.random.randn(3,3).mean()#closed to 0

np.float64(-0.22755594932105694)

In [ ]:
#mean()#center of data
#median()#takes the middle vave
#mode()#most repeated value it it's a chatagore
#std()=sigma=sqrt(samation(xi-mu)**2/n)#xi is index starting to end number-mu is avg



In [17]:
np.mean(data)

np.float64(5.222222222222222)

In [19]:
np.std(data)

np.float64(3.456966485800899)

In [20]:
np.median(data)

np.float64(7.0)

In [21]:
np.var(data)

np.float64(11.950617283950617)

In [23]:
data=np.random.randint(0,100,10)
data

array([73, 51, 90, 62, 63, 43, 17, 44, 62, 97], dtype=int32)

In [27]:
data.min()

np.int32(17)

In [29]:
range=data.max()-data.min()
range

np.int32(80)

In [31]:
data=np.random.randint(0,5,(3,3))
data

array([[4, 3, 3],
       [4, 2, 4],
       [0, 1, 2]], dtype=int32)

In [ ]:
data.sum(axis=0)#gives all row calculation

array([8, 6, 9])

In [33]:
data.max(axis=1)#gives max of all coloum wise

array([4, 4, 2], dtype=int32)

In [34]:
data.min()

np.int32(0)

In [ ]:
data.argmin()#location of min numberS

np.int64(6)

In [5]:
import numpy as np
data=np.random.randint(0,100,(3,3))
data

array([[99, 22, 34],
       [33, 58, 23],
       [30, 43, 44]], dtype=int32)

In [7]:
data.min(axis=1)

array([22, 23, 30], dtype=int32)

In [ ]:
[store ID,sales,customers,inventory,returns]

In [1]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)



[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [3]:
retail_data[:,3].argmax()+1

np.int64(9)

sales/customer
sales/transaction #basket value
sales/units# basket size

In [5]:
#1. What is the **total revenue** generated across all stores?
retail_data[:,1].sum()

np.int64(335000)

In [6]:
#2. Which store recorded the **highest sales**?
retail_data[:,1].argmax()+1

np.int64(9)

In [7]:
#3. Which store recorded the **lowest sales**?
retail_data[:,1].argmin()+1

np.int64(1)

In [4]:
#4. What is the **average daily sales** per store?
retail_data[:,1].mean()

np.float64(33500.0)

In [10]:
#5. How many stores achieved sales **above ₹35,000**?
retail_data
s=np.sum(retail_data[:,1]>35000)
print(s)

3


In [13]:
#6. Which store had the **highest customer footfall**?
s=np.argmax(retail_data[:,2])+1
print(s)

9


In [15]:
#7. What is the **average number of customers** per store?
s=retail_data[:,2].mean()
print(s)

425.0


In [16]:
#8. How many stores have **more than 450 customers**?
s=np.argmax(retail_data[:,2]>450)
print(s)

3


In [18]:
#9. Which store has the **lowest customer count**?
s=np.argmin(retail_data[:,2])+1
print(s)

1


In [31]:
#10.Is there any store where **high sales do not correspond to high customers**?
sal = retail_data[:,1].mean()
cus = retail_data[:,2].mean()
mis = retail_data[(retail_data[:,1] > sal) & (retail_data[:,2] < cus)]
mis

array([[    5, 35000,   420,  1400,    12]])

In [23]:
#11. What is the **total inventory** across all stores?
s=retail_data[:,3].sum()
print(s)





14300


In [26]:
#12. Which store has the **highest inventory stock**?
retail_data[:,3].argmax()+1

np.int64(9)

In [29]:
#13. How many stores have **inventory less than 1300 units**?
d=np.sum(retail_data[:,3]<1300)
print(d)

3


In [33]:
#14. Which store has the **highest return rate** (returns ÷ inventory)?
r=np.argmax(retail_data[:,4]/retail_data[:,3])
print(r)


8


In [37]:
#15. Which stores have **returns greater than 15 units**?
s=retail_data[retail_data[:,4]>15,0]
print(s)


[4 7 9]


In [6]:
#16. Is there a **positive correlation** between sales and customers?
sales = retail_data[:, 1]
customers = retail_data[:, 2]

corr_matrix = np.corrcoef(sales, customers)
correlation = corr_matrix[0, 1]
print(correlation)
if correlation > 0:
    print("Yes")
else:
    print("No")

0.9593636912502479
Yes


In [8]:

#17. Which store has **high customer visits but low sales**?
sales = retail_data[:, 1]
customers = retail_data[:, 2]

avg_sales = np.mean(sales)
avg_customers = np.mean(customers)

condition = (customers > avg_customers) & (sales < avg_sales)

stores = retail_data[condition, 0]
print(stores)

[2]


In [10]:

#18. Which store has **low customers but high sales**?
sales = retail_data[:, 1]
customers = retail_data[:, 2]

avg_sales = np.mean(sales)
avg_customers = np.mean(customers)

condition = (customers < avg_customers) & (sales > avg_sales)

stores = retail_data[condition, 0]
print(stores)

[5]


In [3]:
#19. How many stores have **sales per customer above ₹90**?
s=retail_data[:,1]
c=retail_data[:,2]
s_c=s/c
print(s_c)


[83.33333333 71.11111111 73.68421053 82.         83.33333333 75.
 81.25       75.         81.81818182 80.48780488]


In [7]:

#20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
c=retail_data[:,2]
i=retail_data[:,3]
a_c=np.mean(c)
a_i=np.mean(i)
condition=(c<a_c)&(i>a_i)
s=retail_data[condition,0]
print(s)

[10]


In [4]:
#21.If profit margin is **20% of sales**, what is the **profit per store**?
s= retail_data[:, 1]
p = 0.20
profit_store = s * p

print(profit_store)


[5000. 6400. 5600. 8200. 7000. 5400. 7800. 6000. 9000. 6600.]


In [ ]:
#22. Which store has the **highest profit**?
s= retail_data[:, 1]
p = 0.20
profit_store = (s * p).argmax()

print(profit_store)

8


profit_store

In [6]:
#23. Which store has the **lowest profit**?
s= retail_data[:, 1]
p = 0.20
profit_store = (s * p).argmin()

print(profit_store)

0


In [7]:
#24. If sales increase by **10% next month**, what are the **new sales figures**?
s=retail_data[:,1]
n_s=s*1.10
print(n_s)

[27500. 35200. 30800. 45100. 38500. 29700. 42900. 33000. 49500. 36300.]


In [11]:

#25. How will **total profit** change with the 10% sales increase?
s = np.sum(retail_data[:, 1])     
n_s = s * 1.10                 
p = (n_s * 0.20) - (s * 0.20)  
print(p)


6700.000000000015


In [2]:
#26. Which stores need **inventory restocking** based on sales and current stock?
sales = retail_data[:, 1]
inventory = retail_data[:, 3]
store_ids = retail_data[:, 0]

restock_stores = store_ids[inventory < sales]

print("Stores needing restocking:", restock_stores)


Stores needing restocking: [ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#27. Which stores show **high returns percentage** and might require **quality checks**?
returns_percentage = (retail_data[:, 4] / retail_data[:, 1]) * 100

threshold = 0.05 
high_returns_indices = np.where(returns_percentage > threshold)[0]

high_returns_stores = retail_data[high_returns_indices, 0]
print(high_returns_stores)

[9]


In [3]:
#28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
sales = retail_data[:, 1]
customers = retail_data[:, 2]
inventory_turnover = sales / retail_data[:, 3] 

sales_norm = (sales - sales.min()) / (sales.max() - sales.min())
customers_norm = (customers - customers.min()) / (customers.max() - customers.min())
turnover_norm = (inventory_turnover - inventory_turnover.min()) / (inventory_turnover.max() - inventory_turnover.min())

score = sales_norm + customers_norm + turnover_norm

best_index = np.argmax(score)
best_store_id = int(retail_data[best_index, 0])

print(best_store_id)


9


In [4]:
#29. Which store is the **worst performer overall**?
sales = retail_data[:, 1]
customers = retail_data[:, 2]
inventory_turnover = sales / retail_data[:, 3] 

sales_norm = (sales - sales.min()) / (sales.max() - sales.min())
customers_norm = (customers - customers.min()) / (customers.max() - customers.min())
turnover_norm = (inventory_turnover - inventory_turnover.min()) / (inventory_turnover.max() - inventory_turnover.min())

score = sales_norm + customers_norm + turnover_norm

best_index = np.argmin(score)
best_store_id = int(retail_data[best_index, 0])

print(best_store_id)

1


In [7]:
#30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
sales = retail_data[:, 1]
customers = retail_data[:, 2]

avg_sales = np.mean(sales)
avg_customers = np.mean(customers)

expansion_indices = np.where((sales > avg_sales) & (customers > avg_customers))[0]
expansion_store_ids = retail_data[expansion_indices, 0]

print( expansion_store_ids)


[4 7 9]
