In [1]:
import numpy as np

banking_data = np.array([
    [2001, 2540.75, 720, 15, 5],
    [2002, 3890.50, 650, 8, 3],
    [2003, 1200.00, 580, 20, 2],
    [2004, 8750.25, 810, 5, 10],
    [2005, 4320.10, 700, 18, 6],
    [2006, 2980.40, 690, 12, 4],
    [2007, 6500.00, 750, 9, 7],
    [2008, 780.65, 610, 25, 1],
    [2009, 9420.90, 840, 6, 12],
    [2010, 5200.35, 730, 14, 8]
], dtype=float)

np.set_printoptions(suppress=True, precision=2)

print("\nORIGINAL BANKING DATA:")
print(banking_data)
print(f"\nData shape: {banking_data.shape}")
print(f"Data type: {banking_data.dtype}")





ORIGINAL BANKING DATA:
[[2001.   2540.75  720.     15.      5.  ]
 [2002.   3890.5   650.      8.      3.  ]
 [2003.   1200.    580.     20.      2.  ]
 [2004.   8750.25  810.      5.     10.  ]
 [2005.   4320.1   700.     18.      6.  ]
 [2006.   2980.4   690.     12.      4.  ]
 [2007.   6500.    750.      9.      7.  ]
 [2008.    780.65  610.     25.      1.  ]
 [2009.   9420.9   840.      6.     12.  ]
 [2010.   5200.35  730.     14.      8.  ]]

Data shape: (10, 5)
Data type: float64


In [8]:
# Questions
# Question 1: Array Creation and Manipulation
# Q1.1: Create a 4x4 identity matrix using np.eye()
s=np.eye(4)
print(s)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:

# Q1.2: Create an array of 8 zeros using np.zeros()
z=np.zeros(8)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:

# Q1.3: Create an array of 6 ones using np.ones()
a=np.ones(6)
print(a)

[1. 1. 1. 1. 1. 1.]


In [11]:

# Q1.4: Create an array with values from 0 to 15 using np.arange()
r=np.arange(16)
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [12]:

# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
s=np.linspace(0,100,8)
print(s)

[  0.    14.29  28.57  42.86  57.14  71.43  85.71 100.  ]


In [15]:
# Question 2: Array Attributes and Information
# Q2.1: What is the shape of the banking_data array?
s=banking_data.shape
print(s)

(10, 5)


In [ ]:

# Q2.2: What is the data type of the banking_data array?
# s=type(banking_data)
s=banking_data.dtype
print(s)

float64


In [ ]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
s=banking_data.size
print(s)

Object `array` not found.
50


In [19]:
# Q2.4: What is the number of dimensions of the banking_data array?
d=banking_data.ndim
print(d)

2


In [20]:
# Q2.5: What is the memory size of the banking_data array in bytes?
s=banking_data.nbytes
print(s)

400


In [29]:
# Question 3: Indexing and Slicing
# Q3.1: Extract the first row of banking_data
first_row=banking_data[0]
print(first_row)

[2001.   2540.75  720.     15.      5.  ]


In [31]:
# Q3.2: Extract the last row of banking_data
last_row=banking_data[-1]
print(last_row)

[2010.   5200.35  730.     14.      8.  ]


In [33]:

# Q3.3: Extract the Account_Balance column (column index 1)
s=banking_data[:,1]
print(s)


[2540.75 3890.5  1200.   8750.25 4320.1  2980.4  6500.    780.65 9420.9
 5200.35]


In [34]:
# Q3.4: Extract the first 4 rows and first 3 columns
s=banking_data[:4,:3]
print(s)

[[2001.   2540.75  720.  ]
 [2002.   3890.5   650.  ]
 [2003.   1200.    580.  ]
 [2004.   8750.25  810.  ]]


In [35]:
# Q3.5: Extract rows 3 to 7 (inclusive)
r=banking_data[3:8]
print(r)

[[2004.   8750.25  810.      5.     10.  ]
 [2005.   4320.1   700.     18.      6.  ]
 [2006.   2980.4   690.     12.      4.  ]
 [2007.   6500.    750.      9.      7.  ]
 [2008.    780.65  610.     25.      1.  ]]


In [3]:
# Question 4: Mathematical Operations
# Q4.1: Calculate the sum of all account balances
s=np.sum(banking_data[:,1])
print(f"{s:.2f}")

45583.90


In [4]:

# Q4.2: Calculate the mean account balance
m=np.mean(banking_data[:,1])
print(m)

4558.39


In [5]:

# Q4.3: Calculate the standard deviation of account balances
s=np.std(banking_data[:,1])
print(s)

2793.054626730383


In [6]:
# Q4.4: Calculate the variance of account balances
v=np.var(banking_data[:,1])
print(v)

7801154.147899998


In [7]:
# Q4.5: Calculate the median account balance
m=np.median(banking_data[:,1])
print(m)

4105.3


In [6]:
# Question 5: Statistical Functions
# Q5.1: Find the minimum and maximum account balances
ma=np.max(banking_data[:,1])
mi=np.min(banking_data[:,1])
print(ma)
print(mi)

9420.9
780.65


In [7]:
# Q5.2: Find the minimum and maximum credit scores
ma=np.max(banking_data[:,2])
mi=np.min(banking_data[:,2])
print(ma)
print(mi)

840.0
580.0


In [10]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
percentiles = np.percentile(banking_data[:, 1], [25, 50, 75])
print(percentiles)

[2650.66 4105.3  6175.09]


In [11]:

# Q5.4: Calculate the correlation between account balance and credit score
correlation = np.corrcoef(banking_data[:, 1], banking_data[:, 2])[0, 1]
print(correlation)

0.9293733219708898


In [13]:
# Q5.5: Calculate the covariance between account balance and credit score
cv=np.cov(banking_data[:, 1], banking_data[:, 2])[0, 1]
print(cv)

223335.58888888886


In [14]:
# Question 6: Array Reshaping and Manipulation
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshape=banking_data.reshape(5,10)
print(reshape)

[[2001.   2540.75  720.     15.      5.   2002.   3890.5   650.      8.
     3.  ]
 [2003.   1200.    580.     20.      2.   2004.   8750.25  810.      5.
    10.  ]
 [2005.   4320.1   700.     18.      6.   2006.   2980.4   690.     12.
     4.  ]
 [2007.   6500.    750.      9.      7.   2008.    780.65  610.     25.
     1.  ]
 [2009.   9420.9   840.      6.     12.   2010.   5200.35  730.     14.
     8.  ]]


In [16]:
# Q6.2: Flatten the banking_data to a 1D array
flot=banking_data.flatten()
print(flot)

[2001.   2540.75  720.     15.      5.   2002.   3890.5   650.      8.
    3.   2003.   1200.    580.     20.      2.   2004.   8750.25  810.
    5.     10.   2005.   4320.1   700.     18.      6.   2006.   2980.4
  690.     12.      4.   2007.   6500.    750.      9.      7.   2008.
  780.65  610.     25.      1.   2009.   9420.9   840.      6.     12.
 2010.   5200.35  730.     14.      8.  ]


In [17]:
# Q6.3: Transpose the banking_data
t=banking_data.T
print(t)

[[2001.   2002.   2003.   2004.   2005.   2006.   2007.   2008.   2009.
  2010.  ]
 [2540.75 3890.5  1200.   8750.25 4320.1  2980.4  6500.    780.65 9420.9
  5200.35]
 [ 720.    650.    580.    810.    700.    690.    750.    610.    840.
   730.  ]
 [  15.      8.     20.      5.     18.     12.      9.     25.      6.
    14.  ]
 [   5.      3.      2.     10.      6.      4.      7.      1.     12.
     8.  ]]


In [19]:
# Q6.4: Split the banking_data into 2 equal parts vertically
vs=np.vsplit(banking_data,2)
print(vs)

[array([[2001.  , 2540.75,  720.  ,   15.  ,    5.  ],
       [2002.  , 3890.5 ,  650.  ,    8.  ,    3.  ],
       [2003.  , 1200.  ,  580.  ,   20.  ,    2.  ],
       [2004.  , 8750.25,  810.  ,    5.  ,   10.  ],
       [2005.  , 4320.1 ,  700.  ,   18.  ,    6.  ]]), array([[2006.  , 2980.4 ,  690.  ,   12.  ,    4.  ],
       [2007.  , 6500.  ,  750.  ,    9.  ,    7.  ],
       [2008.  ,  780.65,  610.  ,   25.  ,    1.  ],
       [2009.  , 9420.9 ,  840.  ,    6.  ,   12.  ],
       [2010.  , 5200.35,  730.  ,   14.  ,    8.  ]])]


In [32]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
hs=np.hsplit(banking_data,[2])
# hs=np.array_split(banking_data,2,axis=1)
print(hs[0])
print(hs[1])

[[2001.   2540.75]
 [2002.   3890.5 ]
 [2003.   1200.  ]
 [2004.   8750.25]
 [2005.   4320.1 ]
 [2006.   2980.4 ]
 [2007.   6500.  ]
 [2008.    780.65]
 [2009.   9420.9 ]
 [2010.   5200.35]]
[[720.  15.   5.]
 [650.   8.   3.]
 [580.  20.   2.]
 [810.   5.  10.]
 [700.  18.   6.]
 [690.  12.   4.]
 [750.   9.   7.]
 [610.  25.   1.]
 [840.   6.  12.]
 [730.  14.   8.]]


In [ ]:
# Question 7: Logical Operations and Filtering
# Q7.1: Find customers with account balance greater than $5000
c=banking_data[banking_data[:,1]>5000]
print(c)

[[2004.   8750.25  810.      5.     10.  ]
 [2007.   6500.    750.      9.      7.  ]
 [2009.   9420.9   840.      6.     12.  ]
 [2010.   5200.35  730.     14.      8.  ]]


In [ ]:
# Q7.2: Find customers with credit score greater than 700
cs=banking_data[banking_data[:,2]>700]
print(cs)

[[2001.   2540.75  720.     15.      5.  ]
 [2004.   8750.25  810.      5.     10.  ]
 [2007.   6500.    750.      9.      7.  ]
 [2009.   9420.9   840.      6.     12.  ]
 [2010.   5200.35  730.     14.      8.  ]]


In [54]:
# Q7.3: Find customers with transaction count greater than 10 AND credit score less than 700
tc=banking_data[(banking_data[:,3]>10) & (banking_data[:,2]>700)]
print(tc)

[[2001.   2540.75  720.     15.      5.  ]
 [2010.   5200.35  730.     14.      8.  ]]


In [58]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
count =np.sum((banking_data[:, 1] >= 5000) & (banking_data[:, 1] <= 9000))
print(count)

3


In [63]:
# Q7.5: Find the index of the customer with the highest credit score
hs=np.argmax(banking_data[:,3])
print(hs)

7


In [5]:
# Question 8: Sorting and Searching
# Q8.1: Sort the banking_data by account balance (ascending)
s=banking_data[banking_data[:,1].argsort()]
print(s)

[[2008.    780.65  610.     25.      1.  ]
 [2003.   1200.    580.     20.      2.  ]
 [2001.   2540.75  720.     15.      5.  ]
 [2006.   2980.4   690.     12.      4.  ]
 [2002.   3890.5   650.      8.      3.  ]
 [2005.   4320.1   700.     18.      6.  ]
 [2010.   5200.35  730.     14.      8.  ]
 [2007.   6500.    750.      9.      7.  ]
 [2004.   8750.25  810.      5.     10.  ]
 [2009.   9420.9   840.      6.     12.  ]]


In [6]:

# Q8.2: Sort the banking_data by credit score (descending)
s=banking_data[-banking_data[:,2].argsort()]
print(s)

[[2009.   9420.9   840.      6.     12.  ]
 [2004.   8750.25  810.      5.     10.  ]
 [2010.   5200.35  730.     14.      8.  ]
 [2006.   2980.4   690.     12.      4.  ]
 [2007.   6500.    750.      9.      7.  ]
 [2001.   2540.75  720.     15.      5.  ]
 [2002.   3890.5   650.      8.      3.  ]
 [2005.   4320.1   700.     18.      6.  ]
 [2008.    780.65  610.     25.      1.  ]
 [2003.   1200.    580.     20.      2.  ]]


In [7]:
# Q8.3: Find the indices that would sort the array by years active
s=np.argsort(banking_data[:,4])
print(s)

[7 2 1 5 0 4 6 9 3 8]


In [14]:
# Q8.4: Find the customer with the second highest account balance
s=np.argsort(banking_data[:,1])
ss=s[-2]
print(ss)

3


In [15]:

# Q8.5: Find the customer with the lowest transaction count
l=np.argmin(banking_data[:,3])
print(l)

3


In [16]:
# Question 9: Mathematical Functions
# Q9.1: Calculate the absolute values of all elements
a=np.abs(banking_data)
print(a)

[[2001.   2540.75  720.     15.      5.  ]
 [2002.   3890.5   650.      8.      3.  ]
 [2003.   1200.    580.     20.      2.  ]
 [2004.   8750.25  810.      5.     10.  ]
 [2005.   4320.1   700.     18.      6.  ]
 [2006.   2980.4   690.     12.      4.  ]
 [2007.   6500.    750.      9.      7.  ]
 [2008.    780.65  610.     25.      1.  ]
 [2009.   9420.9   840.      6.     12.  ]
 [2010.   5200.35  730.     14.      8.  ]]


In [17]:
# Q9.2: Calculate the square root of all account balances
s=np.sqrt(banking_data[:,1])
print(s)

[50.41 62.37 34.64 93.54 65.73 54.59 80.62 27.94 97.06 72.11]


In [19]:
# Q9.3: Calculate the square of all credit scores
s=np.square(banking_data[:,2])
print(s)

[518400. 422500. 336400. 656100. 490000. 476100. 562500. 372100. 705600.
 532900.]


In [20]:
# Q9.4: Calculate the exponential of all transaction counts
e=np.exp(banking_data[:,3])
print(e)

[3.27e+06 2.98e+03 4.85e+08 1.48e+02 6.57e+07 1.63e+05 8.10e+03 7.20e+10
 4.03e+02 1.20e+06]


In [21]:
# Q9.5: Calculate the natural logarithm of all account balances
n=np.log(banking_data[:,1])
print(n)

[7.84 8.27 7.09 9.08 8.37 8.   8.78 6.66 9.15 8.56]


In [ ]:
# Question 10: Advanced Operations
# Q10.1: Calculate the cumulative sum of account balances
cs=np.cumsum(banking_data[:,1])
print(cs)

[ 2540.75  6431.25  7631.25 16381.5  20701.6  23682.   30182.   30962.65
 40383.55 45583.9 ]


In [25]:
# Q10.2: Calculate the cumulative product of transaction counts
cp=np.cumprod(banking_data[:,3])
print(cp)

[1.50e+01 1.20e+02 2.40e+03 1.20e+04 2.16e+05 2.59e+06 2.33e+07 5.83e+08
 3.50e+09 4.90e+10]


In [26]:
# Q10.3: Calculate the difference between consecutive account balances
d=np.diff(banking_data[:,1])
print(d)

[ 1349.75 -2690.5   7550.25 -4430.15 -1339.7   3519.6  -5719.35  8640.25
 -4220.55]


In [27]:
# Q10.4: Calculate the gradient of account balances
g=np.gradient(banking_data[:,1])
print(g)

[ 1349.75  -670.38  2429.88  1560.05 -2884.93  1089.95 -1099.88  1460.45
  2209.85 -4220.55]


In [29]:
# Q10.5: Calculate the histogram of account balances with 5 bins
s=np.histogram(banking_data[:,1],bins=5)
print(s)

(array([2, 3, 2, 1, 2]), array([ 780.65, 2508.7 , 4236.75, 5964.8 , 7692.85, 9420.9 ]))


In [30]:
# Question 11: Random Numbers and Simulation
# Q11.1: Generate 6 random integers between 1 and 1000

random = np.random.randint(1, 1000, 6)
print(random)

[730 725 442 872 352 856]


In [31]:
# Q11.2: Generate 6 random floats between 0 and 1
r_f = np.random.random(6)
print(r_f)

[0.26 0.92 0.42 0.02 0.01 0.34]


In [32]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
normal_random = np.random.normal(700, 100, 6)
print(normal_random)

[747.64 674.26 790.79 731.35 725.14 603.13]


In [34]:
# Q11.4: Shuffle the banking_data rows randomly

s_d = banking_data.copy()
np.random.shuffle(s_d)
print(s_d)

[[2005.   4320.1   700.     18.      6.  ]
 [2009.   9420.9   840.      6.     12.  ]
 [2002.   3890.5   650.      8.      3.  ]
 [2010.   5200.35  730.     14.      8.  ]
 [2008.    780.65  610.     25.      1.  ]
 [2006.   2980.4   690.     12.      4.  ]
 [2001.   2540.75  720.     15.      5.  ]
 [2004.   8750.25  810.      5.     10.  ]
 [2003.   1200.    580.     20.      2.  ]
 [2007.   6500.    750.      9.      7.  ]]


In [39]:

# Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
s = np.random.random(4)
print(s)

[0.7  0.29 0.23 0.55]


In [3]:
# Question 12: Linear Algebra Operations
# Q12.1: Calculate the dot product of account balance and credit score columns
d=np.dot(banking_data[:,1],banking_data[:,2])
print(d)

34283421.5


In [6]:
# Q12.2: Calculate the cross product of first two rows
c = np.cross(banking_data[0, :3], banking_data[1, :3])
print(c)

[-1149672.5   140790.   2698309. ]


In [7]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
p = np.linalg.norm(banking_data[:, 1])
print(p)

16905.64211735242


In [21]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
matrix_3x3 = np.array([[2, 3,4], [1, 4,5],[1,2,3]])
determinant = np.linalg.det(matrix_3x3)
print(matrix_3x3)
print(determinant)

[[2 3 4]
 [1 4 5]
 [1 2 3]]
1.9999999999999998


In [24]:
# Q12.5: Calculate the inverse of the 3x3 matrix
matrix_3x3 = np.array([[2, 3, 4], 
                       [1, 4, 5], 
                       [1, 2, 3]])
inverse_matrix = np.linalg.inv(matrix_3x3)
print(inverse_matrix)

[[ 1.  -0.5 -0.5]
 [ 1.   1.  -3. ]
 [-1.  -0.5  2.5]]


In [20]:
# Question 13: String Operations
# Q13.1: Convert all customer IDs to strings
s = banking_data[:, 0].astype(str)
print(s)

['2001.0' '2002.0' '2003.0' '2004.0' '2005.0' '2006.0' '2007.0' '2008.0'
 '2009.0' '2010.0']


In [29]:
# Q13.2: Check if any customer ID contains '100'
customer_ids = banking_data[:, 0].astype(int).astype(str)
c = np.char.find(customer_ids, '100') >= 0
print(c)


[False False False False False False False False False False]


In [33]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
c_str = banking_data[:, 0].astype(int).astype(str)
u=np.char.upper(c_str)
print(u)

['2001' '2002' '2003' '2004' '2005' '2006' '2007' '2008' '2009' '2010']


In [34]:
# Q13.4: Count the length of each customer ID string
c_str = banking_data[:, 0].astype(int).astype(str)
l=np.char.str_len(c_str)
print(l)


[4 4 4 4 4 4 4 4 4 4]


In [ ]:
# Q13.5: Replace '2001' with 'CUST' in customer IDs
c_str = banking_data[:, 0].astype(int).astype(str)
f=np.char.replace(c_str,"2001","CUST")
print(f)

['CUST' '2002' '2003' '2004' '2005' '2006' '2007' '2008' '2009' '2010']


In [41]:
# Question 14: Date and Time Operations
# Q14.1: Convert years active to months
y=banking_data[:,4]*12
print(y)

[ 60.  36.  24. 120.  72.  48.  84.  12. 144.  96.]


In [42]:
# Q14.2: Calculate the average years active
m=np.mean(banking_data[:,4])
print(m)

5.8


In [43]:

# Q14.3: Find customers who have been active for more than 5 years
a=banking_data[banking_data[:,4]>5]
print(a)

[[2004.   8750.25  810.      5.     10.  ]
 [2005.   4320.1   700.     18.      6.  ]
 [2007.   6500.    750.      9.      7.  ]
 [2009.   9420.9   840.      6.     12.  ]
 [2010.   5200.35  730.     14.      8.  ]]


In [44]:
# Q14.4: Calculate the total time all customers have been active (in years)
t=np.sum(banking_data[:,4])
print(t)

58.0


In [45]:
# Q14.5: Find the customer with the shortest time active
m=np.argmin(banking_data[:,4])
print(m)

7


In [6]:
# Question 15: Advanced Array Operations
# Q15.1: Apply a function to calculate 5% interest on all account balances
b=banking_data[:,1]
i=b*1.05
print(b)
print(i)

[2540.75 3890.5  1200.   8750.25 4320.1  2980.4  6500.    780.65 9420.9
 5200.35]
[2667.79 4085.03 1260.   9187.76 4536.11 3129.42 6825.    819.68 9891.94
 5460.37]


In [7]:
# Q15.2: Use np.where to categorize customers by balance ranges
c=np.where(banking_data[:,1]>4000,"rich","average")
print(c)

['average' 'average' 'average' 'rich' 'rich' 'average' 'rich' 'average'
 'rich' 'rich']


In [17]:
# Q15.3: Use np.select to categorize customers by credit score ranges
s=[banking_data[:,2]<600,(banking_data[:,2]>=600) & (banking_data[:,2]<=750),banking_data[:,2]>700]  
c=["ave","good","exc"]
d=np.select(s,c,default='unknown')
print(d)

['good' 'good' 'ave' 'exc' 'good' 'good' 'good' 'good' 'exc' 'good']


In [24]:
# Q15.4: Use np.piecewise to apply different interest rates based on balance
b= banking_data[:, 1]
conditions = [
    b < 3000,
    (b >= 3000) & (b <= 7000),
    b > 7000
]
i= [
    lambda b:b* 1.08, 
    lambda b:b * 1.06,  
    lambda b:b * 1.04  ]  
nb=np.piecewise(b,conditions,i)
banking_data[:,1]=nb
print(banking_data)




[[ 2001.    3200.61   720.      15.       5.  ]
 [ 2002.    4633.65   650.       8.       3.  ]
 [ 2003.    1511.65   580.      20.       2.  ]
 [ 2004.    9842.84   810.       5.      10.  ]
 [ 2005.    5145.31   700.      18.       6.  ]
 [ 2006.    3616.68   690.      12.       4.  ]
 [ 2007.    7595.54   750.       9.       7.  ]
 [ 2008.     983.39   610.      25.       1.  ]
 [ 2009.   10597.23   840.       6.      12.  ]
 [ 2010.    6193.7    730.      14.       8.  ]]


In [ ]:

# Q15.5: Use np.apply_along_axis to calculate the sum of each row

row_sums = np.apply_along_axis(np.sum, axis=1, arr=banking_data)
print(row_sums)


Row-wise sums:
[ 5941.61  7296.65  4116.65 12671.84  7874.31  6328.68 10368.54  3627.39
 13464.23  8955.7 ]


In [4]:
# Question 16: Array Concatenation and Stacking
# Q16.1: Concatenate two arrays horizontally using np.hstack()
import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
z=np.hstack([a,b])
print(z)

[1 2 3 4 4 5 6 7]


In [5]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
z=np.vstack([a,b])
print(z)

[[1 2 3 4]
 [4 5 6 7]]


In [7]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
z=np.concatenate([a,b],axis=0)
print(z)

[1 2 3 4 4 5 6 7]


In [8]:
# Q16.4: Stack arrays depth-wise using np.dstack()
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
z=np.dstack([a,b])
print(z)

[[[1 4]
  [2 5]
  [3 6]
  [4 7]]]


In [9]:

# Q16.5: Create a column stack using np.column_stack()
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
z=np.column_stack([a,b])
print(z)

[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [18]:
# Question 17: Array Splitting Operations
# Q17.1: Split an array into 3 equal parts using np.split()
split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
parts = np.split(split, 3)
print(f"Original array: {split}")
for i, part in enumerate(parts):
    print(f"Part {i+1}: {part}")

Original array: [1 2 3 4 5 6 7 8 9]
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]


In [17]:

# Q17.2: Split an array at specific indices using np.split()
split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = np.split(split, [2, 6])
print(f"Split at indices [2, 6]:")
for i, part in enumerate(indices):
    print(f"Part {i+1}: {part}")

Split at indices [2, 6]:
Part 1: [1 2]
Part 2: [3 4 5 6]
Part 3: [7 8 9]


In [29]:
# Q17.3: Split an array horizontally using np.hsplit()
arr = np.array([[1, 2, 3], [4, 5, 6]])
h = np.hsplit(arr, 3)
print(arr)
for i, part in enumerate(h):
    print(f"Horizontal part {i+1}:\n{part}")

[[1 2 3]
 [4 5 6]]
Horizontal part 1:
[[1]
 [4]]
Horizontal part 2:
[[2]
 [5]]
Horizontal part 3:
[[3]
 [6]]


In [22]:

# Q17.4: Split an array vertically using np.vsplit()
arr = np.array([[1, 2, 3], [4, 5, 6]])
h = np.vsplit(arr, 2)
print(arr)
for i, part in enumerate(h):
    print(f"part {i+1}:\n{part}")

[[1 2 3]
 [4 5 6]]
part 1:
[[1 2 3]]
part 2:
[[4 5 6]]


In [30]:
# Q17.5: Split an array into equal chunks using np.array_split()
split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
chunks = np.array_split(split, 4)
print(f"Split into 4 chunks:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i+1}: {chunk}")

Split into 4 chunks:
Chunk 1: [1 2 3]
Chunk 2: [4 5]
Chunk 3: [6 7]
Chunk 4: [8 9]


In [31]:
# Question 18: Array Repetition and Tiling
# Q18.1: Repeat each element of an array 3 times using np.repeat()
a=np.array([1,2,3,4])
s=np.repeat(a,3)
print(s)

[1 1 1 2 2 2 3 3 3 4 4 4]


In [2]:
# Q18.2: Repeat an entire array 2 times using np.tile()
a=np.array([1,2,3,4])
s=np.tile(a,2)
print(s)

[1 2 3 4 1 2 3 4]


In [3]:
# Q18.3: Repeat a 2D array using np.tile()
a=np.array([[1,2,3,4],[3,4,5,6]])
s=np.tile(a,2)
print(s)

[[1 2 3 4 1 2 3 4]
 [3 4 5 6 3 4 5 6]]


In [2]:
# Q18.4: Create a pattern using np.tile()
a=np.array([0,1,0])
s=np.tile(a,4)
print(a)
print(s)

[0 1 0]
[0 1 0 0 1 0 0 1 0 0 1 0]


In [4]:
# Q18.5: Repeat elements with different counts using np.repeat()
a=np.array([1,2,3,4])
r=[1,3,5,7]
rp=np.repeat(a,r)
print(rp)

[1 2 2 2 3 3 3 3 3 4 4 4 4 4 4 4]


In [7]:
# Question 19: Array Comparison and Logical Operations
# Q19.1: Compare two arrays for equality using np.array_equal()
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.array([1,2,4])
ab=np.array_equal(a,b)
bc=np.array_equal(b,c)
print(ab)
print(bc)

True
False


In [4]:

# Q19.2: Check if arrays are close using np.allclose()
d = np.array([1.0, 2.0, 3.0])
e = np.array([1.001, 2.001, 3.001])
print(d)
print(e)
print(f"Arrays are close: {np.allclose(d,e, atol=0.01)}")

[1. 2. 3.]
[1. 2. 3.]
Arrays are close: True


In [5]:
# Q19.3: Apply logical AND operation between arrays
a=np.array([1,2,3])
b=np.array([1,2,4])
l = np.logical_and(a > 1, b < 3)
print(l)


[False  True False]


In [6]:
# Q19.4: Apply logical OR operation between arrays
a=np.array([1,2,3])
b=np.array([1,2,4])
l = np.logical_or(a > 1, b < 3)
print(l)


[ True  True  True]


In [8]:
# Q19.5: Apply logical NOT operation to an array
b=np.array([1,2,4])
l = np.logical_not(b==1)
print(l)

[False  True  True]


In [10]:
# Question 20: Array Set Operations
# Q20.1: Find unique elements in an array using np.unique()
a=np.array([1,1,2,2,2,3,4,4,3,1,2,4,2,3,5,7,4,6])
s=np.unique(a)
print(s)


[1 2 3 4 5 6 7]


In [12]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7])
i=np.intersect1d(a,b)
print(i)

[4 5]


In [13]:
# Q20.3: Find the union of two arrays using np.union1d()
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7])
i=np.union1d(a,b)
print(i)

[1 2 3 4 5 6 7]


In [15]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7])
d = np.setdiff1d(a, b)
print(d)

[1 2 3]


In [16]:
# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7])
d = np.setxor1d(a, b)
print(d)

[1 2 3 6 7]
